DROP TABLE Students;
DROP TABLE St_Groups;

CREATE TABLE St_Groups (
    ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(50),
    C_VAL NUMBER
);

CREATE TABLE Students (
    ID NUMBER,
    NAME VARCHAR2(50),
    St_Groups_ID NUMBER,
    FOREIGN KEY (St_Groups_ID) REFERENCES St_Groups(ID)
);
/
DROP TRIGGER check_unique_id_students;
CREATE OR REPLACE TRIGGER check_unique_id_students
FOR INSERT OR UPDATE ON Students
COMPOUND TRIGGER

-- Таблица для хранения имен групп, которые должны быть вставлены или обновлены
TYPE t_students_id IS TABLE OF NUMBER INDEX BY PLS_INTEGER;
v_students_id t_students_id;

BEFORE STATEMENT IS
BEGIN
    v_students_id.DELETE;
END BEFORE STATEMENT;

BEFORE EACH ROW IS
BEGIN
    IF INSERTING OR UPDATING THEN
        v_students_id(v_students_id.COUNT + 1) := :NEW.ID;
    END IF;
END BEFORE EACH ROW;

AFTER STATEMENT IS
    v_id_count NUMBER;
BEGIN
    FOR i IN 1 .. v_students_id.COUNT 
    LOOP
        SELECT COUNT(*)
        INTO v_id_count
        FROM Students
        WHERE id = v_students_id(i);
        
        DBMS_OUTPUT.PUT_LINE('Count row ' || v_id_count);
        IF v_id_count <> 1 THEN
            RAISE_APPLICATION_ERROR(-20001, 'This student id exists: ' || v_students_id(i));
        END IF;
    END LOOP;
END AFTER STATEMENT;
END check_unique_id_students;
/
--DROP TRIGGER check_unique_id_groups;
CREATE OR REPLACE TRIGGER check_unique_id_groups
BEFORE INSERT ON St_Groups
FOR EACH ROW
DECLARE
    id_count NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO id_count
    FROM St_Groups
    WHERE ID = :NEW.ID;

    IF id_count > 0 THEN
        RAISE_APPLICATION_ERROR(-20002, 'ID должен быть уникальным в таблице St_Groups');
    END IF;
END;

/
/*
DROP SEQUENCE Students_SEQ;
CREATE SEQUENCE Students_SEQ
START WITH 1
INCREMENT BY 1;
*/

--DROP TRIGGER generate_student_id;
CREATE OR REPLACE TRIGGER generate_student_id
BEFORE INSERT ON Students
FOR EACH ROW
DECLARE 
    max_id NUMBER;
BEGIN
    IF :NEW.ID IS NULL THEN
        SELECT MAX(ID)
        INTO max_id
        FROM Students;
        
        IF max_id IS NOT NULL THEN
            :NEW.ID := max_id + 1;
        ELSE 
            :NEW.ID := 1;
        END IF;
    END IF;
END;
/

/*
DROP SEQUENCE Groups_SEQ;
CREATE SEQUENCE Groups_SEQ
START WITH 1
INCREMENT BY 1;
*/

--DROP TRIGGER generate_groups_id;
CREATE OR REPLACE TRIGGER generate_groups_id
BEFORE INSERT ON St_Groups
FOR EACH ROW
DECLARE 
    max_id NUMBER;
BEGIN
    IF :NEW.ID IS NULL THEN
        SELECT MAX(ID)
        INTO max_id
        FROM St_Groups;
        
        IF max_id IS NOT NULL THEN
            :NEW.ID := max_id + 1;
        ELSE 
            :NEW.ID := 1;
        END IF;
    END IF;
END;
/
--DROP TRIGGER cascade_delete_student;
CREATE OR REPLACE TRIGGER cascade_delete_students
BEFORE DELETE ON St_Groups
FOR EACH ROW
BEGIN
    DELETE FROM Students
    WHERE St_Groups_ID = :OLD.ID;
END;
/
DROP TRIGGER check_group_name;
CREATE OR REPLACE TRIGGER check_group_name
FOR INSERT OR UPDATE ON St_Groups
COMPOUND TRIGGER

-- Таблица для хранения имен групп, которые должны быть вставлены или обновлены
TYPE t_group_names IS TABLE OF VARCHAR2(100) INDEX BY PLS_INTEGER;
v_group_names t_group_names;

BEFORE STATEMENT IS
BEGIN
    v_group_names.DELETE;
END BEFORE STATEMENT;

BEFORE EACH ROW IS
BEGIN
    IF INSERTING OR UPDATING THEN
        v_group_names(v_group_names.COUNT + 1) := :NEW.name;
    END IF;
END BEFORE EACH ROW;

AFTER STATEMENT IS
    v_name_count NUMBER;
BEGIN
    FOR i IN 1 .. v_group_names.COUNT 
    LOOP
        SELECT COUNT(*)
        INTO v_name_count
        FROM St_Groups
        WHERE name = v_group_names(i);
        
        DBMS_OUTPUT.PUT_LINE('Count row ' || v_name_count);
        IF v_name_count <> 1 THEN
            RAISE_APPLICATION_ERROR(-20001, 'This group name exists: ' || v_group_names(i));
        END IF;
    END LOOP;
END AFTER STATEMENT;
END check_group_name;
/
DROP TABLE Students_LOG;
CREATE TABLE Students_LOG (
    ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    ACTION VARCHAR2(10), -- Тип действия (INSERT, UPDATE, DELETE)
    STUDENT_ID NUMBER, -- Идентификатор студента
    STUDENT_NAME VARCHAR2(100), -- Имя студента
    St_Groups_ID NUMBER, -- Идентификатор группы
    LOG_TIMESTAMP TIMESTAMP -- Метка времени аудита
);

DROP TRIGGER students_logger_trigger;
CREATE OR REPLACE TRIGGER students_logger_trigger
AFTER INSERT OR UPDATE OR DELETE ON Students
FOR EACH ROW
DECLARE
    action VARCHAR2(10);
BEGIN
    IF INSERTING THEN
        action := 'INSERT';
        INSERT INTO Students_LOG (ACTION, STUDENT_ID, STUDENT_NAME, St_Groups_ID, LOG_TIMESTAMP)
        VALUES (action, :NEW.ID, :NEW.NAME, :NEW.St_Groups_ID, SYSTIMESTAMP);
    ELSE 
        IF UPDATING THEN
            action := 'UPDATE';
            INSERT INTO Students_LOG (ACTION, STUDENT_ID, STUDENT_NAME, St_Groups_ID, LOG_TIMESTAMP)
            VALUES (action, :NEW.ID, :NEW.NAME, :NEW.St_Groups_ID, SYSTIMESTAMP);
        ELSIF DELETING THEN
            action := 'DELETE';
            INSERT INTO Students_LOG (ACTION, STUDENT_ID, STUDENT_NAME, St_Groups_ID, LOG_TIMESTAMP)
            VALUES (action, :OLD.ID, :OLD.NAME, :OLD.St_Groups_ID, SYSTIMESTAMP);
        END IF;
    END IF;
END;
/
DROP PROCEDURE restore_students_from_log;
CREATE OR REPLACE PROCEDURE restore_students_from_log(
    restore_time TIMESTAMP DEFAULT NULL,
    time_offset INTERVAL DAY TO SECOND DEFAULT NULL
) 
AS
    restore_timestamp TIMESTAMP;
BEGIN
    IF restore_time IS NULL AND time_offset IS NULL THEN
        RAISE_APPLICATION_ERROR(-20001, 'Не указано время восстановления или временное смещение.');
    END IF;

    IF restore_time IS NOT NULL THEN
        restore_timestamp := restore_time;
    ELSE
        restore_timestamp := SYSTIMESTAMP - time_offset;
    END IF;

    FOR log_record IN (SELECT * FROM Students_LOG WHERE LOG_TIMESTAMP <= restore_timestamp) 
    LOOP
        IF log_record.ACTION = 'INSERT' THEN
            IF log_record.STUDENT_ID IS NOT NULL THEN
                DELETE FROM Students WHERE ID = log_record.STUDENT_ID; 
            END IF;
            INSERT INTO Students (ID, NAME, St_Groups_ID)
            VALUES (log_record.STUDENT_ID, log_record.STUDENT_NAME, log_record.St_Groups_ID);
        ELSIF log_record.ACTION = 'UPDATE' THEN
            UPDATE Students
            SET NAME = log_record.STUDENT_NAME, St_Groups_ID = log_record.St_Groups_ID
            WHERE ID = log_record.STUDENT_ID;
        ELSIF log_record.ACTION = 'DELETE' THEN
            DELETE FROM Students WHERE ID = log_record.STUDENT_ID;
        END IF;
    END LOOP;
END;
/

CREATE OR REPLACE TRIGGER update_groups_cval_trigger
 AFTER INSERT OR UPDATE OR DELETE ON Students
 FOR EACH ROW
BEGIN 
    IF UPDATING THEN
        UPDATE St_Groups
        SET C_VAL = C_VAL + 1
        WHERE id = :NEW.St_Groups_ID;

        UPDATE St_Groups
        SET C_VAL = C_VAL - 1
        WHERE id = :OLD.St_Groups_ID;
    END IF;

    IF INSERTING THEN
        UPDATE St_Groups
        SET C_VAL = C_VAL + 1
        WHERE id = :NEW.St_Groups_ID;
    END IF;

    IF DELETING THEN
        UPDATE St_Groups
        SET C_VAL = C_VAL - 1
        WHERE id = :OLD.St_Groups_ID;
    END IF;
END;
/






