DROP TABLE Students_LOG;
CREATE TABLE Students_LOG (
    ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    ACTION VARCHAR2(10), -- Тип действия (INSERT, UPDATE, DELETE)
    STUDENT_ID NUMBER, -- Идентификатор студента
    STUDENT_NAME VARCHAR2(100), -- Имя студента
    St_Groups_ID NUMBER, -- Идентификатор группы
    LOG_TIMESTAMP TIMESTAMP -- Метка времени аудита
);

DROP TRIGGER students_logger_trigger;
CREATE OR REPLACE TRIGGER students_logger_trigger
AFTER INSERT OR UPDATE OR DELETE ON Students
FOR EACH ROW
DECLARE
    action VARCHAR2(10);
BEGIN
    IF INSERTING THEN
        action := 'INSERT';
        INSERT INTO Students_LOG (ACTION, STUDENT_ID, STUDENT_NAME, St_Groups_ID, LOG_TIMESTAMP)
        VALUES (action, :NEW.ID, :NEW.NAME, :NEW.St_Groups_ID, SYSTIMESTAMP);
    ELSE 
        IF UPDATING THEN
            action := 'UPDATE';
            INSERT INTO Students_LOG (ACTION, STUDENT_ID, STUDENT_NAME, St_Groups_ID, LOG_TIMESTAMP)
            VALUES (action, :NEW.ID, :NEW.NAME, :NEW.St_Groups_ID, SYSTIMESTAMP);
        ELSIF DELETING THEN
            action := 'DELETE';
            INSERT INTO Students_LOG (ACTION, STUDENT_ID, STUDENT_NAME, St_Groups_ID, LOG_TIMESTAMP)
            VALUES (action, :OLD.ID, :OLD.NAME, :OLD.St_Groups_ID, SYSTIMESTAMP);
        END IF;
    END IF;
END;
/




