version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: airport_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: airport_db
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - "7777:5432"

  mysql_db:
    image: mysql:latest
    container_name: airport_mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: airport_mysql_db
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD: mysql_password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"   
volumes:
  data:
  mysql_data: